In [8]:
import numpy as np
A = np.zeros((4,4),)
A[1::2,::2] = 1
A[0::2,1::2] = 1
print(A)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [3]:
A = np.zeros((5,5)) # Матрица 5x5 
A += np.arange(5) # Значение в строках от 0 до 4
print(A)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [4]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.10624885 0.16471599 0.33845434]
  [0.69120078 0.41749081 0.58286299]
  [0.36259203 0.01081764 0.51834604]]

 [[0.5337806  0.40916191 0.81815534]
  [0.64984616 0.73020366 0.35200705]
  [0.47649133 0.8416919  0.07061523]]

 [[0.10280621 0.22189285 0.00776259]
  [0.04021396 0.23302104 0.52467988]
  [0.74441693 0.48951674 0.83985721]]]


In [5]:
b = np.ones((5, 5))
b[1:-1, 1:-1] = 0
print(b)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
arr = np.arange(1, 10)
print(np.sort(arr)[::-1])

[9 8 7 6 5 4 3 2 1]


In [9]:
a = int(input('Введите кол-во строк:'))
b = int(input('Введите кол-во столбцов:'))
A = np.zeros((a, b), int)

print(A)
print(np.shape(A)) # форма
print(np.size(A)) # размер
print(np.ndim(A)) # размерность

Введите кол-во строк:6
Введите кол-во столбцов:7
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
(6, 7)
42
2


In [8]:
a = np.array((3, 0, 3))
b = np.array((3, 3, 3))

square = np.square(a - b)
sum_square = np.sum(square)

distance = np.sqrt(sum_square)
print(distance)

3.0


In [4]:
import pandas as pd
url='https://raw.githubusercontent.com/akmand/datasets/main/airlines.csv'
dataframe=pd.read_csv(url)
dataframe.head(7)

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0      CO     269         SFO       IAH          3    15     205      1
1      US    1558         PHX       CLT          3    15     222      1
2      AA    2400         LAX       DFW          3    20     165      1
3      AA    2466         SFO       DFW          3    20     195      1
4      AS     108         ANC       SEA          3    30     202      0
5      CO    1094         LAX       IAH          3    30     181      1
6      DL    1768         LAX       MSP          3    30     220      0

In [5]:
url='https://raw.githubusercontent.com/akmand/datasets/main/airlines.csv'

dataframe=pd.read_csv(url)
dataframe.head(10) # первые 10 строк


Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0      CO     269         SFO       IAH          3    15     205      1
1      US    1558         PHX       CLT          3    15     222      1
2      AA    2400         LAX       DFW          3    20     165      1
3      AA    2466         SFO       DFW          3    20     195      1
4      AS     108         ANC       SEA          3    30     202      0
5      CO    1094         LAX       IAH          3    30     181      1
6      DL    1768         LAX       MSP          3    30     220      0
7      DL    2722         PHX       DTW          3    30     228      0
8      DL    2606         SFO       MSP          3    35     216      1
9      AA    2538         LAS       ORD          3    40     200      1

In [28]:
dataframe.tail(3) # последние 3 строки


Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
539380      FL     609         SFO       MKE          5  1439     255      0
539381      UA      78         HNL       SFO          5  1439     313      1
539382      US    1442         LAX       PHL          5  1439     301      1

In [29]:
dataframe.shape # кол-во строк и столбцов


(539383, 8)

In [30]:
dataframe.describe() # описательная статистика для любых числовых столбцов


Flight      DayOfWeek           Time         Length  \
count  539383.000000  539383.000000  539383.000000  539383.000000   
mean     2427.928630       3.929668     802.728963     132.202007   
std      2067.429837       1.914664     278.045911      70.117016   
min         1.000000       1.000000      10.000000       0.000000   
25%       712.000000       2.000000     565.000000      81.000000   
50%      1809.000000       4.000000     795.000000     115.000000   
75%      3745.000000       5.000000    1035.000000     162.000000   
max      7814.000000       7.000000    1439.000000     655.000000   

               Delay  
count  539383.000000  
mean        0.445442  
std         0.497015  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         1.000000  
max         1.000000

In [6]:
dataframe.iloc[2:6] # для выбора 1 или нескольких строк, либо значений


Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
2      AA    2400         LAX       DFW          3    20     165      1
3      AA    2466         SFO       DFW          3    20     195      1
4      AS     108         ANC       SEA          3    30     202      0
5      CO    1094         LAX       IAH          3    30     181      1

In [33]:
dataframe[dataframe['Airline'] == 'US'].head(5) # новый фрейм из условия

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
1       US    1558         PHX       CLT          3    15     222      1
15      US     498         DEN       CLT          3    55     179      0
24      US     122         ANC       PHX          3   113     327      1
31      US    1011         EWR       CLT          3   300     111      0
32      US    1983         BOS       CLT          3   300     135      0

In [35]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
dataframe = pd.read_csv('https://raw.githubusercontent.com/akmand/datasets/master/iris.csv')


dataframe[['sepal_length_cm']] = MinMaxScaler().fit_transform(dataframe[['sepal_length_cm']])

dataframe[['sepal_width_cm']] = StandardScaler().fit_transform(dataframe[['sepal_width_cm']])
dataframe


sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]